# Self-signed issuer to bootstrap the root CA
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-bootstrap
spec:
  selfSigned: {}
---
# Root CA Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-lab-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "Home Lab Root CA"
  secretName: home-lab-root-ca-secret
  duration: 87600h # 10 years
  renewBefore: 8760h # Renew 1 year before expiry
  subject:
    organizations:
      - "Home Lab"
    countries:
      - "US"
    provinces:
      - "CA"
    localities:
      - "San Francisco"
    organizationalUnits:
      - "IT Department"
  privateKey:
    algorithm: RSA
    size: 4096
  issuerRef:
    name: selfsigned-bootstrap
    kind: ClusterIssuer
    group: cert-manager.io
---
# ClusterIssuer that uses the root CA
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: home-lab-ca-issuer
spec:
  ca:
    secretName: home-lab-root-ca-secret
